// <auto-generated />
using BankierScrapper.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BankierScrapper.Repositories.Migrations
{
    [DbContext(typeof(BankierContext))]
    [Migration("20180416202009_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankierScrapper.Repositories.DbModels.CompanyDb", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Url");

                    b.HasKey("Name");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("BankierScrapper.Repositories.DbModels.RecommendationDb", b =>
                {
                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Institution");

                    b.Property<int>("CompanyId");

                    b.Property<decimal>("ChangePotential");

                    b.Property<string>("Character");

                    b.Property<string>("CompanyName");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("ReleasePrice");

                    b.Property<decimal>("TargetPrice");

                    b.HasKey("ReleaseDate", "Institution", "CompanyId");

                    b.HasAlternateKey("CompanyId", "Institution", "ReleaseDate");

                    b.HasIndex("CompanyName");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("BankierScrapper.Repositories.DbModels.TimeSeriesDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CaptureDate");

                    b.Property<int>("CompanyId");

                    b.Property<string>("CompanyName");

                    b.Property<decimal>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName");

                    b.ToTable("TimeSeries");
                });

            modelBuilder.Entity("BankierScrapper.Repositories.DbModels.RecommendationDb", b =>
                {
                    b.HasOne("BankierScrapper.Repositories.DbModels.CompanyDb", "Company")
                        .WithMany("Recommendations")
                        .HasForeignKey("CompanyName");
                });

            modelBuilder.Entity("BankierScrapper.Repositories.DbModels.TimeSeriesDb", b =>
                {
                    b.HasOne("BankierScrapper.Repositories.DbModels.CompanyDb", "Company")
                        .WithMany("TimeSeries")
                        .HasForeignKey("CompanyName");
                });
#pragma warning restore 612, 618
        }
    }
}
